FROM ubuntu:16.04
MAINTAINER Hao Yuan <freegleyuan@foxmail.com>

ENV HOME /root

RUN apt-get update \
	&& apt-get install -y supervisor \
		apt-utils \
		aufs-tools \
		automake \
		bash-completion \
		binutils-mingw-w64 \
		bsdmainutils \
		btrfs-tools \
		build-essential \
		clang \
		cmake \
		createrepo \
		curl \
		dpkg-sig \
		gcc-mingw-w64 \
		git \
		iptables \
		jq \
		less \
		libapparmor-dev \
		libcap-dev \
		libltdl-dev \
		libnl-3-dev \
		libprotobuf-c0-dev \
		libprotobuf-dev \
		libsystemd-journal-dev \
		libtool \
		libzfs-dev \
		mercurial \
		net-tools \
		pkg-config \
		protobuf-compiler \
		protobuf-c-compiler \
		python-dev \
		python-mock \
		python-pip \
		python-websocket \
		tar \
		ubuntu-zfs \
		vim \
		vim-common \
		xfsprogs \
		zip \
		openssh-server vim-tiny \
		xfce4 xfce4-goodies \
		x11vnc xvfb \
		firefox \
		mplayer \
		xserver-xspice xinput \
	&& apt-get autoclean \
	&& apt-get autoremove \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /root

ADD startup.sh ./
ADD supervisord.conf ./

EXPOSE 5900
EXPOSE 5910
EXPOSE 22

ENTRYPOINT ["./startup.sh"]
